repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.15.14"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/PyCQA/isort
    rev: "9.0.0a3"
    hooks:
      - id: isort
        name: isort
        language_version: python3
